version: '3'

services:
  redis-master:
    image: redis:latest
    container_name: redis-master
    ports:
      - "6379:6379"

  redis-slave1:
    image: redis:latest
    container_name: redis-slave1
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  redis-slave2:
    image: redis:latest
    container_name: redis-slave2
    command: redis-server --slaveof redis-master 6379
    depends_on:
      - redis-master

  sentinel:
    image: redis:latest
    container_name: redis-sentinel
    command: redis-sentinel /etc/redis/sentinel.conf
    ports:
      - "26379:26379"
    depends_on:
      - redis-master
      - redis-slave1
      - redis-slave2
    volumes:
      - ./sentinel.conf:/etc/redis/sentinel.conf