version: '3.8'

services:
    redis-master:
        image: redis:7.2-alpine # Versi spesifik
        container_name: redis-master
        restart: unless-stopped
        ports:
            - '6379:6379'
        volumes:
            - redis_master_data:/data # Persistensi data
        # command: redis-server --requirepass password_yang_aman # Jika pakai password
        networks:
            - redis-net

    redis-slave1:
        image: redis:7.2-alpine # Versi spesifik
        container_name: redis-slave1
        restart: unless-stopped
        command: redis-server --slaveof redis-master 6379 # --masterauth password_yang_aman
        depends_on:
            - redis-master
        volumes:
            - redis_slave1_data:/data # Persistensi data
        networks:
            - redis-net

    redis-slave2:
        image: redis:7.2-alpine # Versi spesifik
        container_name: redis-slave2
        restart: unless-stopped
        command: redis-server --slaveof redis-master 6379 # --masterauth password_yang_aman
        depends_on:
            - redis-master
        volumes:
            - redis_slave2_data:/data # Persistensi data
        networks:
            - redis-net

    # Menjalankan 3 node Sentinel untuk High Availability
    sentinel1:
        image: redis:7.2-alpine # Versi spesifik
        container_name: redis-sentinel-1
        restart: unless-stopped
        ports:
            - '26379:26379'
        volumes:
            - ./sentinel.conf:/etc/redis/sentinel.conf
        command: redis-sentinel /etc/redis/sentinel.conf
        depends_on:
            - redis-master
            - redis-slave1
            - redis-slave2
        networks:
            - redis-net

    sentinel2:
        image: redis:7.2-alpine
        container_name: redis-sentinel-2
        restart: unless-stopped
        volumes:
            - ./sentinel.conf:/etc/redis/sentinel.conf
        command: redis-sentinel /etc/redis/sentinel.conf
        depends_on:
            - redis-master
            - redis-slave1
            - redis-slave2
        networks:
            - redis-net

    sentinel3:
        image: redis:7.2-alpine
        container_name: redis-sentinel-3
        restart: unless-stopped
        volumes:
            - ./sentinel.conf:/etc/redis/sentinel.conf
        command: redis-sentinel /etc/redis/sentinel.conf
        depends_on:
            - redis-master
            - redis-slave1
            - redis-slave2
        networks:
            - redis-net

# Mendefinisikan jaringan kustom
networks:
    redis-net:
        driver: bridge

# Mendefinisikan named volumes
volumes:
    redis_master_data:
    redis_slave1_data:
    redis_slave2_data:
