version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.4.6
        hostname: zookeeper
        container_name: zookeeper
        ports:
            - '2181:2181'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_SERVERS: zookeeper:2888:3888

    kafka:
        image: confluentinc/cp-kafka:7.4.6
        hostname: kafka
        container_name: kafka
        ports:
            - '9092:9092'
            - '29092:29092'
            - '29093:29093'
        environment:
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9092,DOCKER://host.docker.internal:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,DOCKER:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
            KAFKA_BROKER_ID: 1
            KAFKA_LOG4J_LOGGERS: 'kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO'
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_JMX_PORT: 9999
            KAFKA_JMX_HOSTNAME: ${DOCKER_HOST_IP:-127.0.0.1}
            KAFKA_AUTHORIZER_CLASS_NAME: kafka.security.authorizer.AclAuthorizer
            KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: 'true'
        depends_on:
            - zookeeper

    akhq:
        image: tchiotludo/akhq:latest
        container_name: akhq
        ports:
            - 8070:8080
        environment:
            AKHQ_CONFIGURATION: |
                akhq:
                  connections:
                    local:
                      properties:
                        bootstrap.servers: "kafka:19092"
                        zookeeper.connect: "zookeeper:2181"

    postgres:
        container_name: postgres
        image: postgres:latest
        environment:
            POSTGRES_USER: root
            POSTGRES_PASSWORD: sam123
        ports:
            - '5432:5432'
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

    pgadmin:
        container_name: pgadmin
        image: dpage/pgadmin4:latest
        environment:
            PGADMIN_DEFAULT_EMAIL: admin@pgadmin.com
            PGADMIN_DEFAULT_PASSWORD: admin
        ports:
            - '5050:80'

    redis:
        image: redis:latest
        container_name: redis
        ports:
            - '6379:6379'

networks:
    host:
        external: true
    local-network:
        driver: bridge
volumes:
    postgresql:
    postgresql_data:

