version: '3.8'

services:
    mysql:
        image: mysql:8.4 # 1. Menggunakan versi spesifik
        container_name: my_mysql
        restart: unless-stopped # 2. Kebijakan restart yang lebih fleksibel
        ports:
            - '3306:3306'
        # 3. Menggunakan env_file untuk keamanan
        env_file:
            - .env
        volumes:
            # 4. Menggunakan Named Volume dengan komentar yang benar
            - data:/var/lib/mysql
        # 5. Baris 'expose' dihapus karena tidak perlu

volumes:
    data:
