version: '3.8'

services:
    zookeeper:
        image: confluentinc/cp-zookeeper:7.6.1 # Versi spesifik
        hostname: zookeeper
        container_name: zookeeper
        restart: unless-stopped # Kebijakan restart
        ports:
            - '2181:2181'
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_SERVERS: zookeeper:2888:3888
        volumes: # Menambahkan persistensi data
            - zookeeper_data:/var/lib/zookeeper/data
            - zookeeper_log:/var/lib/zookeeper/log

    kafka:
        image: confluentinc/cp-kafka:7.6.1 # Versi spesifik & cocok dengan zookeeper
        container_name: kafka
        restart: unless-stopped # Kebijakan restart
        depends_on:
            - zookeeper
        ports:
            - '29092:29092'
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            # Variabel tambahan untuk best practice
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
            KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
            KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
        volumes: # Menambahkan persistensi data
            - kafka_data:/var/lib/kafka/data

    akhq:
        image: tchiotludo/akhq:0.25.0 # Versi spesifik
        container_name: akhq
        restart: unless-stopped # Kebijakan restart
        ports:
            - '8080:8080'
        environment:
            AKHQ_CONFIGURATION: |
                akhq:
                  connections:
                    local:
                      properties:
                        bootstrap.servers: "kafka:9092"
        depends_on:
            - kafka

# Mendeklarasikan named volumes yang digunakan
volumes:
    zookeeper_data:
    zookeeper_log:
    kafka_data:
