version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes: 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    external: true