version: "3.8"

services:
  postgres:
    container_name: postgres
    image: postgres
    env_file:
      - database.env
    ports:
      - "5432:5432"
    volumes: 

      # Bind Mount
      - ./pgdata:/var/lib/postgresql/data

      # Volume Storage
      # - pgdata:/var/lib/postgresql/data

# Uncomment line below if you want to use Volume storage
# volumes:
#   pgdata:
#     external: true