version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:4.2
    ports:
      - "27017:27017"
    command: mongod
    volumes: 
      - ./mongo:/data/db
volumes:
  mongo:
    external: true