version: "3.5"

services:
  mongo1:
    container_name: mongo1
    image: mongo:4.2
    ports:
      - 27017:27017
    command: mongod --replSet my-mongo-set
    networks: 
      - mongo_replica_set
    volumes: 
      - ./mongo1:/data/db
  mongo2:
    container_name: mongo2
    image: mongo:4.2
    ports:
      - 27018:27017
    command: mongod --replSet my-mongo-set
    networks: 
      - mongo_replica_set
    volumes: 
      - ./mongo2:/data/db
  mongo3:
    container_name: mongo3
    image: mongo:4.2
    ports:
      - 27019:27017
    command: mongod --replSet my-mongo-set
    networks: 
      - mongo_replica_set
    volumes: 
      - ./mongo2:/data/db

networks: 
  mongo_replica_set:
    name: mongo_replica_set

volumes:
  mongo1:
    external: true
  mongo2:
    external: true
  mongo3:
    external: true