version: "3.7"

services:
  mongo-new1:
    container_name: mongo-new1
    image: mongo:6
    ports:
      - 27017:27017
    command: mongod --replSet rs0
    networks: 
      - mongo-net
    volumes: 
      - ./init-replica-set.js:/docker-entrypoint-initdb.d/init-replica-set.js

  mongo-new2:
    container_name: mongo-new2
    image: mongo:6
    ports:
      - 27018:27017
    command: mongod --replSet rs0
    networks: 
      - mongo-net

  mongo-new3:
    container_name: mongo-new3
    image: mongo:6
    ports:
      - 27019:27017
    command: mongod --replSet rs0
    networks: 
      - mongo-net


networks: 
  mongo-net:
    driver: bridge