version: "3.8"

services:
  mongo:
    container_name: mongo
    image: mongo:4.4
    ports:
      - "27017:27017"
    command: mongod
    volumes: 
      # Bind Mount
      - ./mongodata:/data/db

      # Volume Storage
      # - mongodata:/data/db

# Uncomment line below if you want to use Volume storage
# volumes:
#   mongodata:
#     external: true