version: "3.8"

services:
  redis:
    container_name: redis
    image: redis:5
    ports:
      - "6379:6379"
    volumes:

      # Bind Mount
      - ./redis_data:/data
      
      # Volume Storage
      # - redis_data:/data

# Uncomment line below if you want to use Volume storage
# volumes: 
#   redis_data:
#     external: true