version: "3.8"

services:
  redis_2:
    container_name: redis_2
    image: redis:5
    ports:
      - "6378:6379"
    volumes:
      - redis_data_2:/data

volumes: 
  redis_data_2:
    external: true